### ISSUE TITLE
It's only possible to start one instance (and also, it's not possible to start any instance of type C)

### ISSUE THREAD

**Issue by jbmorgado** [DualCoder/vgpu_unlock#54] opened 2021-06-09 15:45 UTC
Hi all.

I am using a 1080 Ti and no matter the size of the instance I choose, I can only assign the vgpu to one machine. When I try a second one, I get the error:

```
kvm: -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:07:00.0/00000000-0000-0000-0000-000000000101,id=hostpci0,bus=pci.0,addr=0x10,rombar=0: vfio 00000000-0000-0000-0000-000000000101: error getting device from group 29: Connection timed out
Verify all devices in group 29 are bound to vfio-<bus> or pci-stub and not already in use`
```

Also, instances of type C (for computing) don't work with the very same error.

Finally, it says it's possible to create instances of sizes up to 24Gb, although the 1080 Ti only has 11Gb VRAM.

**Comment by DualCoder** [comment] 2021-06-09 21:07
> I can only assign the vgpu to one machine

Yes this is expected. To run multiple VMs on a single GPU you will need to create one vGPU for each VM. Also all vGPUs need to be of the same type and size.

> Also, instances of type C (for computing) don't work with the very same error.

For further information please provide the output of `dmesg` and `journalctl -u nvidia-vgpu-mgr`.

> Finally, it says it's possible to create instances of sizes up to 24Gb, although the 1080 Ti only has 11Gb VRAM.

This is also expected. The way vgpu\_unlock functions is by reporting the PCI ID of the actual card as the PCI ID of a Tesla/Quadro card that supports vGPU. In this case all profiles for the Tesla/Quadro will show up, even if they are not working. So for your 1080 Ti all profiles for the Tesla P40 will show up, you will just have to be careful to not use more vRAM than available on the actual card.

**Comment by DualCoder** [comment] 2021-07-11 12:28
I'm closing this since it is working as intended. And instance type C is discussed in #55.

**Closed as completed by DualCoder** 2021-07-11 12:28 UTC
